<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\data_activator.svg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\data_activator.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Connector.SqlServer\Connector.AzureEventHub.csproj" />
  </ItemGroup>

</Project>
